### ISSUE TITLE
Migrate Forestry to TinaCMS

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/ddmal.github.io#112]
Forestry.io is no longer maintained. We may want to migrate to TinaCMS when possible. See [link](https://tina.io/forestry/).

**Comment by PythonSemicolon** [comment]
Under Ich's instruction, I have removed the CMS entirely and deployed the static website under the `deforested` branch. This is now the version associated to the https://ddmal.music.mcgill.ca/ domain.

**Comment by yinanazhou** [comment]
@PythonSemicolon Could you please update readme about this change?
