### ISSUE TITLE
Ich's page is empty

### ISSUE THREAD

**Issue by napulen** [DDMAL/ddmal.github.io#12]
The DDMAL page about [Ich ](https://ddmal.music.mcgill.ca/lab_members/principal_investigator/ichiro_fujinaga/) is currently empty.

Maybe it should point out to Ich's [website ](http://www.music.mcgill.ca/~ich/).

Alternatively, we could add some information into it.
@fujinaga @evansavage @vigliensoni 

On a second look, I realized this also applies to [Emily's](https://ddmal.music.mcgill.ca/lab_members/project_manager/emily_hopkins/) @emilyhopkins. 

If the page(s) are intentionally empty, please disregard this issue.

**Comment by emilyhopkins** [comment]
For Ich: maybe we could add his picture there and then just link his site? He keeps it up-to-date and I'd rather avoid duplicating efforts in favour of having slightly nonstandard entries for people.

Mine not being there is 100% my fault and not intentional, it's on my list 😬

**Comment by fujinaga** [comment]
Picture added. Link added.
