### ISSUE TITLE
link to ddmal wiki is broken

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/ddmal.github.io#123]
on https://ddmal.music.mcgill.ca/resources/ - it links to wiki.simssa.ca, whereas it needs to link to wiki.internal.simssa.ca

@kqct, is this substitution correct?

**Comment by zhannaklimanova** [comment]
Do you _Music Tech Wiki (requires VPN)_ link? 

![Screenshot 2023-07-17 at 2 26 02 PM](https://github.com/DDMAL/ddmal.github.io/assets/59708333/a4e40494-1288-45f2-b1bf-f1849e6517b2)

**Comment by fujinaga** [comment]
It should be “DDMAL Wiki” which does require VPN.
The link should be: https://wiki.internal.simssa.ca/

**Comment by zhannaklimanova** [comment]
This issue has been resolved.
