### ISSUE TITLE
Update lab picture

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/ddmal.github.io#9]
There should be a much recent picture, taken last summer. @emilyhopkins do you happen to have it?

**Comment by emilyhopkins** [comment]
yes I do! 
![DSC_9555](https://user-images.githubusercontent.com/13374693/70456333-ee53f280-1a7b-11ea-97a7-b70e1ef5a341.JPG)
![DSC_9556](https://user-images.githubusercontent.com/13374693/70456335-ee53f280-1a7b-11ea-85e7-ab4fe9055d0a.JPG)
